spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/snipstash
    username: postgres
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
      allowed-headers: Content-Type,Authorization

server:
  port: 5000

app:
  jwt:
    secret: your_jwt_secret_key_here_make_it_very_long_and_secure_in_production
    expiration: 86400000 # 24 hours in milliseconds
  email:
    verification:
      expiration: 300 # 5 minutes in seconds 